version: '3.7'
services:
  app-prod:
    container_name: devfactory-website-fo-prod
    profiles: ["prod"]
    # user: ${GROUP_ID}:${USER_ID}
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    ports:
      - 82:3000
  app-dev:
    container_name: devfactory-website-fo-dev
    profiles: ["dev"]
    # user: ${GROUP_ID}:${USER_ID}
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000