# build environment
FROM node:14.17.3-alpine3.14 as build
ENV HOST=0.0.0.0
WORKDIR /app
COPY package.json ./
COPY yarn.lock ./
RUN yarn --check-files

COPY . .
RUN yarn build

EXPOSE 3000
CMD ["yarn", "start"]