FROM node:17-alpine3.14

# create destination directory
RUN mkdir -p /dev-factory-website
WORKDIR /dev-factory-website

# update and install dependency
RUN apk update && apk upgrade
RUN apk add git

# copy the package.json, yarn.lock
COPY package.json yarn.lock ./
# copy the app, note .dockerignore
COPY . /dev-factory-website/
RUN yarn install

# expose 5000 on container
EXPOSE 3000

# set app serving to permissive / assigned
ENV NUXT_HOST=0.0.0.0
# set app port
ENV NUXT_PORT=3000

# start the app
CMD [ "yarn", "dev" ]