name: shell Command 

on: [push]

jobs: 
  run-shell-commands: 
    runs-on: ubuntu-20.04 
    steps:
      - name: echo a string 
        run: echo "test github actions" 
      - name: multiline script 
        run: |
          node -v 
          npm -v   